version: 2

sphinx:
  configuration: WORC/doc/conf.py

build:
  os: "ubuntu-22.04"
  tools:
    python: "3.11"

python:
  install:
    - method: pip
      pip:
        - git+https://github.com/Svdvoort/PREDICTFastr.git@py311#egg=PREDICT
        - numpy<=1.26.3
    - method: pip
      path: .