version: 2

sphinx:
  configuration: WORC/doc/conf.py

build:
  os: "ubuntu-22.04"
  tools:
    python: "3.11"

python:
  install:
    - requirements: WORC/doc/requirements-pre-numpy.txt
    - requirements: WORC/doc/requirements-pre-predict.txt
    - requirements: WORC/doc/requirements.txt
    - method: pip
      path: .