version: 2

sphinx:
  configuration: WORC/doc/conf.py

build:
  os: "ubuntu-22.04"
  tools:
    python: "3.11"

python:
  install:
    - requirements: doc/requirements-doc-numpy.txt
    - requirements: doc/requirements-doc-predict.txt
    - method: pip
      path: .