version: 2

sphinx:
  configuration: WORC/doc/conf.py

build:
  os: "ubuntu-22.04"
  tools:
    python: "3.11"

python:
  install:
      # preinstall setuptools first
    - method: pip
      requirements:
        - setuptools
    - requirements: WORC/doc/requirements-pre-numpy.txt
    - requirements: WORC/doc/requirements.txt