version: 2

sphinx:
  configuration: WORC/doc/conf.py

build:
  os: "ubuntu-22.04"
  tools:
    python: "3.11"

python:
  install:
    # 1. Install patched dependency from GitHub first
    - method: pip
      path: git+https://github.com/Svdvoort/PREDICTFastr.git@py311#egg=PREDICT

    # 2. Then pre-requirements (e.g., numpy pinning)
    - requirements: requirements-pre.txt

    # 3. Finally, install your own package
    - method: pip
      path: .