version: 2

sphinx:
  configuration: WORC/doc/conf.py

build:
  os: "ubuntu-22.04"
  tools:
    python: "3.11"
  apt_packages:
    - python3-distutils

python:
  install:
    - requirements: requirements-pre.txt
    - method: pip
      path: .