# .readthedocs.yml

version: 2

sphinx:
  configuration: WORC/doc/conf.py

build:
  os: "ubuntu-20.04"
  tools:
    python: "3.7"

python:
  install:
    - requirements: WORC/doc/requirements.txt
    - method: pip
      path: .