# .readthedocs.yml

version: 2

sphinx:
  configuration: WORC/doc/conf.py

formats: []

python:
  version: 3.7
  install:
    - requirements: requirements.txt
    - method: pip
      path: .
  system_packages: true
