# .readthedocs.yml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

version: 2

sphinx:
  configuration: WORC/doc/conf.py

build:
  os: "ubuntu-22.04"
  tools:
    python: "3.11"

python:
  # First, install numpy explicitly
  - requirements: docs/requirements-pre.txt
  # Then install your package using pyproject.toml
  - method: pip
    path: .