# .readthedocs.yml

version: 2

sphinx:
  configuration: WORC/doc/conf.py

formats: []

# Set the version of OS
build:
  os: ubuntu-20.04  # <- add this line

python:
  version: 3.7
  install:
    - requirements: requirements.txt
    - method: pip
      path: .
  system_packages: true
